python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal 850

python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal 850
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal 150
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal 250
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal 450
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal 650
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal 850

python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT 150 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT 250 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT 450 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT 650 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT 850 --mu_signal -850

python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT -150 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT -250 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT -450 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT -650 --mu_signal -850
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal -150
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal -250
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal -450
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal -650
python plot_significance.py --sample_type sig --mu_BDT -850 --mu_signal -850